// Emoji data for picker and search
export const EMOJI_LIST = [
    { emoji: '😀', keywords: ['grinning', 'smile', 'happy'], category: 'smileys' },
    { emoji: '😃', keywords: ['smile', 'happy', 'joy'], category: 'smileys' },
    { emoji: '😄', keywords: ['smile', 'happy', 'joy'], category: 'smileys' },
    { emoji: '😁', keywords: ['grin', 'smile', 'happy'], category: 'smileys' },
    { emoji: '😆', keywords: ['laugh', 'satisfied'], category: 'smileys' },
    { emoji: '😅', keywords: ['sweat', 'smile', 'relief'], category: 'smileys' },
    { emoji: '😂', keywords: ['joy', 'tears', 'laugh'], category: 'smileys' },
    { emoji: '🤣', keywords: ['rofl', 'laugh', 'funny'], category: 'smileys' },
    { emoji: '😊', keywords: ['blush', 'smile', 'happy'], category: 'smileys' },
    { emoji: '😇', keywords: ['innocent', 'angel'], category: 'smileys' },
    { emoji: '😉', keywords: ['wink', 'flirt'], category: 'smileys' },
    { emoji: '😍', keywords: ['heart', 'love', 'eyes'], category: 'hearts' },
    { emoji: '🥰', keywords: ['love', 'hearts', 'smile'], category: 'hearts' },
    { emoji: '😘', keywords: ['kiss', 'love'], category: 'hearts' },
    { emoji: '😗', keywords: ['kiss', 'smile'], category: 'hearts' },
    { emoji: '😙', keywords: ['kiss', 'smile'], category: 'hearts' },
    { emoji: '😚', keywords: ['kiss', 'closed', 'eyes'], category: 'hearts' },
    { emoji: '😋', keywords: ['yum', 'delicious'], category: 'smileys' },
    { emoji: '😜', keywords: ['wink', 'tongue', 'playful'], category: 'smileys' },
    { emoji: '😝', keywords: ['tongue', 'playful'], category: 'smileys' },
    { emoji: '😛', keywords: ['tongue', 'silly'], category: 'smileys' },
    { emoji: '🤑', keywords: ['money', 'rich', 'dollar'], category: 'objects' },
    { emoji: '🤗', keywords: ['hug', 'smile'], category: 'smileys' },
    { emoji: '🤩', keywords: ['star', 'eyes', 'amazed'], category: 'symbols' },
    { emoji: '🥳', keywords: ['party', 'celebrate', 'birthday'], category: 'activity' },
    { emoji: '😎', keywords: ['cool', 'sunglasses'], category: 'smileys' },
    { emoji: '🤓', keywords: ['nerd', 'glasses'], category: 'smileys' },
    { emoji: '🧐', keywords: ['monocle', 'curious'], category: 'smileys' },
    { emoji: '😏', keywords: ['smirk', 'confident'], category: 'smileys' },
    { emoji: '😒', keywords: ['unamused', 'bored'], category: 'smileys' },
    { emoji: '😞', keywords: ['disappointed', 'sad'], category: 'smileys' },
    { emoji: '😔', keywords: ['sad', 'pensive'], category: 'smileys' },
    { emoji: '😢', keywords: ['cry', 'sad', 'tear'], category: 'smileys' },
    { emoji: '😭', keywords: ['cry', 'tears', 'sad'], category: 'smileys' },
    { emoji: '😤', keywords: ['triumph', 'angry'], category: 'smileys' },
    { emoji: '😠', keywords: ['angry', 'mad'], category: 'smileys' },
    { emoji: '😡', keywords: ['angry', 'rage'], category: 'smileys' },
    { emoji: '🤬', keywords: ['cursing', 'angry'], category: 'smileys' },
    { emoji: '🤯', keywords: ['mind', 'blown'], category: 'symbols' },
    { emoji: '😳', keywords: ['flushed', 'embarrassed'], category: 'smileys' },
    { emoji: '🥺', keywords: ['pleading', 'puppy'], category: 'smileys' },
    { emoji: '😱', keywords: ['scream', 'fear'], category: 'smileys' },
    { emoji: '😨', keywords: ['fear', 'scared'], category: 'smileys' },
    { emoji: '😰', keywords: ['anxious', 'cold', 'sweat'], category: 'smileys' },
    { emoji: '😥', keywords: ['sad', 'relief'], category: 'smileys' },
    { emoji: '😓', keywords: ['sweat', 'sad'], category: 'smileys' },
    { emoji: '🤔', keywords: ['thinking', 'question'], category: 'symbols' },
    { emoji: '🤭', keywords: ['oops', 'embarrassed'], category: 'smileys' },
    { emoji: '🤫', keywords: ['shush', 'quiet'], category: 'smileys' },
    { emoji: '🤥', keywords: ['lying', 'pinocchio'], category: 'smileys' },
    { emoji: '😶', keywords: ['silent', 'blank'], category: 'smileys' },
    { emoji: '😐', keywords: ['neutral', 'meh'], category: 'smileys' },
    { emoji: '😑', keywords: ['expressionless'], category: 'smileys' },
    { emoji: '😬', keywords: ['grimace', 'awkward'], category: 'smileys' },
    { emoji: '🙄', keywords: ['eyeroll', 'annoyed'], category: 'smileys' },
    { emoji: '😯', keywords: ['surprised', 'wow'], category: 'smileys' },
    { emoji: '😦', keywords: ['frown', 'sad'], category: 'smileys' },
    { emoji: '😧', keywords: ['anguished', 'shocked'], category: 'smileys' },
    { emoji: '😮', keywords: ['open', 'mouth', 'surprised'], category: 'smileys' },
    { emoji: '😲', keywords: ['astonished', 'surprised'], category: 'smileys' },
    { emoji: '🥱', keywords: ['yawn', 'tired'], category: 'smileys' },
    { emoji: '😴', keywords: ['sleep', 'zzz'], category: 'smileys' },
    { emoji: '🤤', keywords: ['drool', 'hungry'], category: 'smileys' },
    { emoji: '😪', keywords: ['sleepy', 'tired'], category: 'smileys' },
    { emoji: '😵', keywords: ['dizzy', 'dead'], category: 'smileys' },
    { emoji: '🤐', keywords: ['zipper', 'mouth', 'secret'], category: 'objects' },
    { emoji: '🥴', keywords: ['woozy', 'drunk'], category: 'smileys' },
    { emoji: '🤢', keywords: ['nausea', 'sick'], category: 'smileys' },
    { emoji: '🤮', keywords: ['vomit', 'sick'], category: 'smileys' },
    { emoji: '🤧', keywords: ['sneeze', 'sick'], category: 'smileys' },
    { emoji: '😷', keywords: ['mask', 'sick'], category: 'objects' },
    { emoji: '🤒', keywords: ['thermometer', 'sick'], category: 'objects' },
    { emoji: '🤕', keywords: ['head', 'bandage', 'hurt'], category: 'objects' },
    { emoji: '🤠', keywords: ['cowboy', 'hat'], category: 'objects' },
    { emoji: '😈', keywords: ['devil', 'smile'], category: 'symbols' },
    { emoji: '👿', keywords: ['angry', 'devil'], category: 'symbols' },
    { emoji: '👹', keywords: ['ogre', 'monster'], category: 'nature' },
    { emoji: '👺', keywords: ['goblin', 'monster'], category: 'nature' },
    { emoji: '💀', keywords: ['skull', 'dead'], category: 'nature' },
    { emoji: '👻', keywords: ['ghost', 'halloween'], category: 'nature' },
    { emoji: '👽', keywords: ['alien', 'ufo'], category: 'nature' },
    { emoji: '🤖', keywords: ['robot', 'ai'], category: 'objects' },
    { emoji: '🎃', keywords: ['pumpkin', 'halloween'], category: 'nature' },
    { emoji: '😺', keywords: ['cat', 'smile'], category: 'nature' },
    { emoji: '😸', keywords: ['cat', 'grin'], category: 'nature' },
    { emoji: '😹', keywords: ['cat', 'joy'], category: 'nature' },
    { emoji: '😻', keywords: ['cat', 'love'], category: 'nature' },
    { emoji: '😼', keywords: ['cat', 'smirk'], category: 'nature' },
    { emoji: '😽', keywords: ['cat', 'kiss'], category: 'nature' },
    { emoji: '🙀', keywords: ['cat', 'scared'], category: 'nature' },
    { emoji: '😿', keywords: ['cat', 'cry'], category: 'nature' },
    { emoji: '😾', keywords: ['cat', 'angry'], category: 'nature' },
    // activity emojis
    { emoji: '⚽', keywords: ['soccer', 'football', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏀', keywords: ['basketball', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏈', keywords: ['american football', 'activity', 'sports'], category: 'activity' },
    { emoji: '⚾', keywords: ['baseball', 'activity', 'sports'], category: 'activity' },
    { emoji: '🎾', keywords: ['tennis', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏐', keywords: ['volleyball', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏉', keywords: ['rugby', 'activity', 'sports'], category: 'activity' },
    { emoji: '🎱', keywords: ['billiards', '8ball', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏓', keywords: ['ping pong', 'table tennis', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏸', keywords: ['badminton', 'activity', 'sports'], category: 'activity' },
    { emoji: '🥅', keywords: ['goal', 'net', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏒', keywords: ['ice hockey', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏑', keywords: ['field hockey', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏏', keywords: ['cricket', 'activity', 'sports'], category: 'activity' },
    { emoji: '🥍', keywords: ['lacrosse', 'activity', 'sports'], category: 'activity' },
    { emoji: '🥊', keywords: ['boxing', 'activity', 'sports'], category: 'activity' },
    { emoji: '🥋', keywords: ['martial arts', 'activity', 'sports'], category: 'activity' },
    { emoji: '⛳', keywords: ['golf', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏹', keywords: ['archery', 'activity', 'sports'], category: 'activity' },
    { emoji: '🎣', keywords: ['fishing', 'activity', 'sports'], category: 'activity' },
    { emoji: '🥌', keywords: ['curling', 'activity', 'sports'], category: 'activity' },
    { emoji: '⛸️', keywords: ['ice skate', 'activity', 'sports'], category: 'activity' },
    { emoji: '🛷', keywords: ['sled', 'activity', 'sports'], category: 'activity' },
    { emoji: '🛹', keywords: ['skateboard', 'activity', 'sports'], category: 'activity' },
    { emoji: '🛼', keywords: ['roller skate', 'activity', 'sports'], category: 'activity' },
    { emoji: '🛶', keywords: ['canoe', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏂', keywords: ['snowboard', 'activity', 'sports'], category: 'activity' },
    { emoji: '⛷️', keywords: ['skier', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏄', keywords: ['surfing', 'activity', 'sports'], category: 'activity' },
    { emoji: '🚣', keywords: ['rowing', 'activity', 'sports'], category: 'activity' },
    { emoji: '🏊', keywords: ['swimming', 'activity', 'sports'], category: 'activity' },
    { emoji: '🤽', keywords: ['water polo', 'activity', 'sports'], category: 'activity' },
    { emoji: '🚴', keywords: ['biking', 'activity', 'sports'], category: 'activity' },
    { emoji: '🚵', keywords: ['mountain biking', 'activity', 'sports'], category: 'activity' },
    // food emojis
    { emoji: '🍏', keywords: ['green apple', 'fruit', 'food'], category: 'food' },
    { emoji: '🍎', keywords: ['red apple', 'fruit', 'food'], category: 'food' },
    { emoji: '🍐', keywords: ['pear', 'fruit', 'food'], category: 'food' },
    { emoji: '🍊', keywords: ['tangerine', 'fruit', 'food'], category: 'food' },
    { emoji: '🍋', keywords: ['lemon', 'fruit', 'food'], category: 'food' },
    { emoji: '🍌', keywords: ['banana', 'fruit', 'food'], category: 'food' },
    { emoji: '🍉', keywords: ['watermelon', 'fruit', 'food'], category: 'food' },
    { emoji: '🍇', keywords: ['grapes', 'fruit', 'food'], category: 'food' },
    { emoji: '🍓', keywords: ['strawberry', 'fruit', 'food'], category: 'food' },
    { emoji: '🫐', keywords: ['blueberry', 'fruit', 'food'], category: 'food' },
    { emoji: '🍈', keywords: ['melon', 'fruit', 'food'], category: 'food' },
    { emoji: '🍒', keywords: ['cherry', 'fruit', 'food'], category: 'food' },
    { emoji: '🍑', keywords: ['peach', 'fruit', 'food'], category: 'food' },
    { emoji: '🥭', keywords: ['mango', 'fruit', 'food'], category: 'food' },
    { emoji: '🍍', keywords: ['pineapple', 'fruit', 'food'], category: 'food' },
    { emoji: '🥥', keywords: ['coconut', 'fruit', 'food'], category: 'food' },
    { emoji: '🥝', keywords: ['kiwi', 'fruit', 'food'], category: 'food' },
    { emoji: '🍅', keywords: ['tomato', 'fruit', 'food'], category: 'food' },
    { emoji: '🍆', keywords: ['eggplant', 'brinjal', 'vegetable', 'food'], category: 'food' },
    { emoji: '🥑', keywords: ['avocado', 'fruit', 'food'], category: 'food' },
    { emoji: '🥦', keywords: ['broccoli', 'vegetable', 'food'], category: 'food' },
    { emoji: '🥬', keywords: ['leafy green', 'vegetable', 'food'], category: 'food' },
    { emoji: '🥒', keywords: ['cucumber', 'vegetable', 'food'], category: 'food' },
    { emoji: '🌶️', keywords: ['hot pepper', 'vegetable', 'food'], category: 'food' },
    { emoji: '🌽', keywords: ['corn', 'vegetable', 'food'], category: 'food' },
    { emoji: '🥕', keywords: ['carrot', 'vegetable', 'food'], category: 'food' },
    { emoji: '🧄', keywords: ['garlic', 'vegetable', 'food'], category: 'food' },
    { emoji: '🧅', keywords: ['onion', 'vegetable', 'food'], category: 'food' },
    { emoji: '🥔', keywords: ['potato', 'vegetable', 'food'], category: 'food' },
    { emoji: '🍠', keywords: ['sweet potato', 'vegetable', 'food'], category: 'food' },
    { emoji: '🥐', keywords: ['croissant', 'bread', 'food'], category: 'food' },
    { emoji: '🍞', keywords: ['bread', 'food'], category: 'food' },
    { emoji: '🥖', keywords: ['baguette', 'bread', 'food'], category: 'food' },
    { emoji: '🥨', keywords: ['pretzel', 'bread', 'food'], category: 'food' },
    { emoji: '🥯', keywords: ['bagel', 'bread', 'food'], category: 'food' },
    { emoji: '🥞', keywords: ['pancake', 'food'], category: 'food' },
    { emoji: '🧇', keywords: ['waffle', 'food'], category: 'food' },
    { emoji: '🧀', keywords: ['cheese', 'food'], category: 'food' },
    { emoji: '🍖', keywords: ['meat', 'food'], category: 'food' },
    { emoji: '🍗', keywords: ['poultry', 'food'], category: 'food' },
    { emoji: '🥩', keywords: ['steak', 'food'], category: 'food' },
    { emoji: '🥓', keywords: ['bacon', 'food'], category: 'food' },
    { emoji: '🍔', keywords: ['burger', 'food'], category: 'food' },
    { emoji: '🍟', keywords: ['fries', 'food'], category: 'food' },
    { emoji: '🍕', keywords: ['pizza', 'food'], category: 'food' },
    { emoji: '🌭', keywords: ['hotdog', 'food'], category: 'food' },
    { emoji: '🥪', keywords: ['sandwich', 'food'], category: 'food' },
    { emoji: '🌮', keywords: ['taco', 'food'], category: 'food' },
    { emoji: '🌯', keywords: ['burrito', 'food'], category: 'food' },
    { emoji: '🥙', keywords: ['stuffed flatbread', 'food'], category: 'food' },
    { emoji: '🧆', keywords: ['falafel', 'food'], category: 'food' },
    { emoji: '🥚', keywords: ['egg', 'food'], category: 'food' },
    { emoji: '🍳', keywords: ['cooking', 'food'], category: 'food' },
    { emoji: '🥘', keywords: ['shallow pan', 'food'], category: 'food' },
    { emoji: '🍲', keywords: ['pot of food'], category: 'food' },
    { emoji: '🥣', keywords: ['bowl with spoon', 'food'], category: 'food' },
    { emoji: '🥗', keywords: ['green salad', 'food'], category: 'food' },
    { emoji: '🍿', keywords: ['popcorn', 'food'], category: 'food' },
    { emoji: '🧈', keywords: ['butter', 'food'], category: 'food' },
    { emoji: '🧊', keywords: ['ice', 'food'], category: 'food' },
    { emoji: '🥤', keywords: ['cup with straw', 'drink', 'food'], category: 'food' },
    { emoji: '🧃', keywords: ['beverage box', 'drink', 'food'], category: 'food' },
    { emoji: '🧉', keywords: ['mate', 'drink', 'food'], category: 'food' },
    { emoji: '🍵', keywords: ['tea', 'drink', 'food'], category: 'food' },
    { emoji: '☕', keywords: ['coffee', 'drink', 'food'], category: 'food' },
    { emoji: '🍼', keywords: ['baby bottle', 'drink', 'food'], category: 'food' },
    { emoji: '🥛', keywords: ['glass of milk', 'drink', 'food'], category: 'food' },
    { emoji: '🍺', keywords: ['beer', 'drink', 'food'], category: 'food' },
    { emoji: '🍻', keywords: ['beer mugs', 'drink', 'food'], category: 'food' },
    { emoji: '🥂', keywords: ['clinking glasses', 'drink', 'food'], category: 'food' },
    { emoji: '🍷', keywords: ['wine', 'drink', 'food'], category: 'food' },
    { emoji: '🥃', keywords: ['whiskey', 'drink', 'food'], category: 'food' },
    { emoji: '🍸', keywords: ['cocktail', 'drink', 'food'], category: 'food' },
    { emoji: '🍹', keywords: ['tropical drink', 'drink', 'food'], category: 'food' },
    { emoji: '🍾', keywords: ['bottle with popping cork', 'drink', 'food'], category: 'food' },
    { emoji: '🥄', keywords: ['spoon', 'food'], category: 'food' },
    { emoji: '🍴', keywords: ['fork and knife', 'food'], category: 'food' },
    { emoji: '🥢', keywords: ['chopsticks', 'food'], category: 'food' },
    // travel emojis
    { emoji: '🚗', keywords: ['car', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚕', keywords: ['taxi', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚙', keywords: ['suv', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚌', keywords: ['bus', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚎', keywords: ['trolleybus', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🏎️', keywords: ['racing car', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚓', keywords: ['police car', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚑', keywords: ['ambulance', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚒', keywords: ['fire engine', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚚', keywords: ['delivery truck', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚛', keywords: ['articulated lorry', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚜', keywords: ['tractor', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🛵', keywords: ['scooter', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🏍️', keywords: ['motorcycle', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚲', keywords: ['bicycle', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🛴', keywords: ['kick scooter', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚨', keywords: ['police light', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🚦', keywords: ['traffic light', 'travel', 'signal'], category: 'travel' },
    { emoji: '🚧', keywords: ['construction', 'travel', 'barrier'], category: 'travel' },
    { emoji: '⛽', keywords: ['fuel pump', 'travel', 'gas'], category: 'travel' },
    { emoji: '🚁', keywords: ['helicopter', 'travel', 'air'], category: 'travel' },
    { emoji: '🛩️', keywords: ['small airplane', 'travel', 'air'], category: 'travel' },
    { emoji: '✈️', keywords: ['airplane', 'travel', 'air'], category: 'travel' },
    { emoji: '🛫', keywords: ['airplane departure', 'travel', 'air'], category: 'travel' },
    { emoji: '🛬', keywords: ['airplane arrival', 'travel', 'air'], category: 'travel' },
    { emoji: '🚀', keywords: ['rocket', 'travel', 'space'], category: 'travel' },
    { emoji: '🛸', keywords: ['flying saucer', 'travel', 'space'], category: 'travel' },
    { emoji: '🚢', keywords: ['ship', 'travel', 'water'], category: 'travel' },
    { emoji: '⛴️', keywords: ['ferry', 'travel', 'water'], category: 'travel' },
    { emoji: '🛥️', keywords: ['motor boat', 'travel', 'water'], category: 'travel' },
    { emoji: '⛵', keywords: ['sailboat', 'travel', 'water'], category: 'travel' },
    { emoji: '🚤', keywords: ['speedboat', 'travel', 'water'], category: 'travel' },
    { emoji: '🛳️', keywords: ['passenger ship', 'travel', 'water'], category: 'travel' },
    { emoji: '⚓', keywords: ['anchor', 'travel', 'water'], category: 'travel' },
    { emoji: '🚉', keywords: ['station', 'travel', 'train'], category: 'travel' },
    { emoji: '🚄', keywords: ['high-speed train', 'travel', 'train'], category: 'travel' },
    { emoji: '🚅', keywords: ['bullet train', 'travel', 'train'], category: 'travel' },
    { emoji: '🚈', keywords: ['light rail', 'travel', 'train'], category: 'travel' },
    { emoji: '🚇', keywords: ['metro', 'travel', 'train'], category: 'travel' },
    { emoji: '🚊', keywords: ['tram', 'travel', 'train'], category: 'travel' },
    { emoji: '🚋', keywords: ['tram car', 'travel', 'train'], category: 'travel' },
    { emoji: '🚍', keywords: ['oncoming bus', 'travel', 'vehicle'], category: 'travel' },
    { emoji: '🏰', keywords: ['castle', 'travel', 'place'], category: 'travel' },
    { emoji: '🗼', keywords: ['tokyo tower', 'travel', 'place'], category: 'travel' },
    { emoji: '🗽', keywords: ['statue of liberty', 'travel', 'place'], category: 'travel' },
    { emoji: '🗿', keywords: ['moai', 'travel', 'place'], category: 'travel' },
    { emoji: '🌉', keywords: ['bridge', 'travel', 'place'], category: 'travel' },
    { emoji: '🌆', keywords: ['cityscape', 'travel', 'place'], category: 'travel' },
    { emoji: '🏯', keywords: ['japanese castle', 'travel', 'place'], category: 'travel' },
    { emoji: '🏟️', keywords: ['stadium', 'travel', 'place'], category: 'travel' },
    { emoji: '🗺️', keywords: ['map', 'travel', 'place'], category: 'travel' },
    { emoji: '🛣️', keywords: ['motorway', 'travel', 'place'], category: 'travel' },
    { emoji: '🛤️', keywords: ['railway', 'travel', 'place'], category: 'travel' },
    { emoji: '🐶', keywords: ['dog', 'animal', 'pet'], category: 'animals' },
    { emoji: '🐱', keywords: ['cat', 'animal', 'pet'], category: 'animals' },
    { emoji: '🐭', keywords: ['mouse', 'animal', 'pet'], category: 'animals' },
    { emoji: '🐹', keywords: ['hamster', 'animal', 'pet'], category: 'animals' },
    { emoji: '🐰', keywords: ['rabbit', 'animal', 'pet'], category: 'animals' },
    { emoji: '🦊', keywords: ['fox', 'animal'], category: 'animals' },
    { emoji: '🐻', keywords: ['bear', 'animal'], category: 'animals' },
    { emoji: '🐼', keywords: ['panda', 'animal'], category: 'animals' },
    { emoji: '🐨', keywords: ['koala', 'animal'], category: 'animals' },
    { emoji: '🐯', keywords: ['tiger', 'animal'], category: 'animals' },
    { emoji: '🦁', keywords: ['lion', 'animal'], category: 'animals' },
    { emoji: '🐮', keywords: ['cow', 'animal'], category: 'animals' },
    { emoji: '🐷', keywords: ['pig', 'animal'], category: 'animals' },
    { emoji: '🐸', keywords: ['frog', 'animal'], category: 'animals' },
    { emoji: '🐵', keywords: ['monkey', 'animal'], category: 'animals' },
    { emoji: '🙈', keywords: ['see-no-evil', 'monkey', 'animal'], category: 'animals' },
    { emoji: '🙉', keywords: ['hear-no-evil', 'monkey', 'animal'], category: 'animals' },
    { emoji: '🙊', keywords: ['speak-no-evil', 'monkey', 'animal'], category: 'animals' },
    { emoji: '🐔', keywords: ['chicken', 'animal', 'bird'], category: 'animals' },
    { emoji: '🐧', keywords: ['penguin', 'animal', 'bird'], category: 'animals' },
    { emoji: '🐦', keywords: ['bird', 'animal'], category: 'animals' },
    { emoji: '🐤', keywords: ['chick', 'animal', 'bird'], category: 'animals' },
    { emoji: '🐣', keywords: ['hatching chick', 'animal', 'bird'], category: 'animals' },
    { emoji: '🐥', keywords: ['front-facing chick', 'animal', 'bird'], category: 'animals' },
    { emoji: '🦆', keywords: ['duck', 'animal', 'bird'], category: 'animals' },
    { emoji: '🦅', keywords: ['eagle', 'animal', 'bird'], category: 'animals' },
    { emoji: '🦉', keywords: ['owl', 'animal', 'bird'], category: 'animals' },
    { emoji: '🦇', keywords: ['bat', 'animal'], category: 'animals' },
    { emoji: '🐺', keywords: ['wolf', 'animal'], category: 'animals' },
    { emoji: '🐗', keywords: ['boar', 'animal'], category: 'animals' },
    { emoji: '🐴', keywords: ['horse', 'animal'], category: 'animals' },
    { emoji: '🦄', keywords: ['unicorn', 'animal'], category: 'animals' },
    { emoji: '🐝', keywords: ['bee', 'insect', 'nature'], category: 'nature' },
    { emoji: '🐛', keywords: ['bug', 'insect', 'nature'], category: 'nature' },
    { emoji: '🦋', keywords: ['butterfly', 'insect', 'nature'], category: 'nature' },
    { emoji: '🐌', keywords: ['snail', 'nature'], category: 'nature' },
    { emoji: '🐞', keywords: ['lady beetle', 'insect', 'nature'], category: 'nature' },
    { emoji: '🐜', keywords: ['ant', 'insect', 'nature'], category: 'nature' },
    { emoji: '🦗', keywords: ['cricket', 'insect', 'nature'], category: 'nature' },
    { emoji: '🕷️', keywords: ['spider', 'insect', 'nature'], category: 'nature' },
    { emoji: '🦂', keywords: ['scorpion', 'insect', 'nature'], category: 'nature' },
    { emoji: '🐢', keywords: ['turtle', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐍', keywords: ['snake', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦎', keywords: ['lizard', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦖', keywords: ['t-rex', 'dinosaur', 'nature'], category: 'nature' },
    { emoji: '🦕', keywords: ['sauropod', 'dinosaur', 'nature'], category: 'nature' },
    { emoji: '🐙', keywords: ['octopus', 'sea', 'nature'], category: 'nature' },
    { emoji: '🦑', keywords: ['squid', 'sea', 'nature'], category: 'nature' },
    { emoji: '🦐', keywords: ['shrimp', 'sea', 'nature'], category: 'nature' },
    { emoji: '🦞', keywords: ['lobster', 'sea', 'nature'], category: 'nature' },
    { emoji: '🦀', keywords: ['crab', 'sea', 'nature'], category: 'nature' },
    { emoji: '🐡', keywords: ['blowfish', 'sea', 'nature'], category: 'nature' },
    { emoji: '🐠', keywords: ['tropical fish', 'sea', 'nature'], category: 'nature' },
    { emoji: '🐟', keywords: ['fish', 'sea', 'nature'], category: 'nature' },
    { emoji: '🐬', keywords: ['dolphin', 'sea', 'nature'], category: 'nature' },
    { emoji: '🐳', keywords: ['spouting whale', 'sea', 'nature'], category: 'nature' },
    { emoji: '🐋', keywords: ['whale', 'sea', 'nature'], category: 'nature' },
    { emoji: '🦭', keywords: ['seal', 'sea', 'nature'], category: 'nature' },
    { emoji: '🐊', keywords: ['crocodile', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐅', keywords: ['tiger', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐆', keywords: ['leopard', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦓', keywords: ['zebra', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦍', keywords: ['gorilla', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦧', keywords: ['orangutan', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐘', keywords: ['elephant', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦛', keywords: ['hippopotamus', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦏', keywords: ['rhinoceros', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐪', keywords: ['camel', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐫', keywords: ['bactrian camel', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦒', keywords: ['giraffe', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦘', keywords: ['kangaroo', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦬', keywords: ['bison', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐃', keywords: ['water buffalo', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐂', keywords: ['ox', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐄', keywords: ['cow', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐎', keywords: ['horse', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐖', keywords: ['pig', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐏', keywords: ['ram', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐑', keywords: ['sheep', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦙', keywords: ['llama', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐐', keywords: ['goat', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦌', keywords: ['deer', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐕', keywords: ['dog', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐩', keywords: ['poodle', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦮', keywords: ['guide dog', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐈', keywords: ['cat', 'animal', 'nature'], category: 'nature' },
    { emoji: '🐓', keywords: ['rooster', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦃', keywords: ['turkey', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦚', keywords: ['peacock', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦜', keywords: ['parrot', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦢', keywords: ['swan', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦩', keywords: ['flamingo', 'animal', 'nature'], category: 'nature' },
    { emoji: '🕊️', keywords: ['dove', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦤', keywords: ['dodo', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦥', keywords: ['sloth', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦦', keywords: ['otter', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦨', keywords: ['skunk', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦡', keywords: ['badger', 'animal', 'nature'], category: 'nature' },
    { emoji: '🦫', keywords: ['beaver', 'animal', 'nature'], category: 'nature' },
    { emoji: '👋', keywords: ['wave', 'hand', 'hello'], category: 'people' },
    { emoji: '🖕', keywords: ['middle finger', 'insult', 'offensive', 'rude'], category: 'people' },
    { emoji: '🤚', keywords: ['raised back of hand', 'stop'], category: 'people' },
    { emoji: '🖐️', keywords: ['raised hand', 'five'], category: 'people' },
    { emoji: '✋', keywords: ['raised hand', 'high five'], category: 'people' },
    { emoji: '🖖', keywords: ['vulcan salute', 'spock'], category: 'people' },
    { emoji: '🤏', keywords: ['pinching hand', 'small', 'insult', 'derogatory'], category: 'people' },
    { emoji: '👌', keywords: ['ok', 'hand'], category: 'people' },
    { emoji: '👍', keywords: ['thumbs up', 'like'], category: 'people' },
    { emoji: '👎', keywords: ['thumbs down', 'dislike'], category: 'people' },
    { emoji: '✊', keywords: ['raised fist', 'power'], category: 'people' },
    { emoji: '👊', keywords: ['fist bump', 'bro'], category: 'people' },
    { emoji: '👉', keywords: ['pointing finger', 'finger', 'used in combinations', 'suggestive'], category: 'people' },
    { emoji: '👈', keywords: ['pointing finger', 'finger', 'used in combinations', 'suggestive'], category: 'people' },
    { emoji: '👆', keywords: ['pointing finger', 'finger', 'used in combinations', 'suggestive'], category: 'people' },
    { emoji: '👇', keywords: ['pointing finger', 'finger', 'used in combinations', 'suggestive'], category: 'people' },
    { emoji: '🙏', keywords: ['pray', 'namaste', 'high five'], category: 'people' },
    { emoji: '🤝', keywords: ['handshake', 'deal'], category: 'people' },
    { emoji: '💪', keywords: ['bicep', 'strong', 'muscle'], category: 'people' },
    { emoji: '🧠', keywords: ['brain', 'mind', 'smart'], category: 'people' },
    { emoji: '👀', keywords: ['eyes', 'looking'], category: 'people' },
    { emoji: '👁️', keywords: ['eye', 'sight'], category: 'people' },
    { emoji: '👅', keywords: ['tongue', 'taste'], category: 'people' },
    { emoji: '👄', keywords: ['lips', 'kiss'], category: 'people' },
    { emoji: '👶', keywords: ['baby', 'infant'], category: 'people' },
    { emoji: '👧', keywords: ['girl', 'child'], category: 'people' },
    { emoji: '👦', keywords: ['boy', 'child'], category: 'people' },
    { emoji: '👩', keywords: ['woman', 'person'], category: 'people' },
    { emoji: '👨', keywords: ['man', 'person'], category: 'people' },
    { emoji: '🧑‍⚕️', keywords: ['doctor', 'nurse', 'health'], category: 'people' },
    { emoji: '🧑‍🎓', keywords: ['student', 'graduate'], category: 'people' },
    { emoji: '🧑‍🏫', keywords: ['teacher', 'professor'], category: 'people' },
    { emoji: '🧑‍💻', keywords: ['coder', 'developer', 'tech'], category: 'people' },

    // More Objects
    { emoji: '💡', keywords: ['idea', 'lightbulb', 'light'], category: 'objects' },
    { emoji: '💻', keywords: ['laptop', 'computer', 'tech'], category: 'objects' },
    { emoji: '📱', keywords: ['phone', 'mobile'], category: 'objects' },
    { emoji: '⌚', keywords: ['watch', 'time'], category: 'objects' },
    { emoji: '📷', keywords: ['camera', 'photo'], category: 'objects' },
    { emoji: '🎵', keywords: ['music', 'note'], category: 'objects' },
    { emoji: '🎶', keywords: ['music', 'notes'], category: 'objects' },
    { emoji: '📚', keywords: ['books', 'study', 'library'], category: 'objects' },
    { emoji: '💵', keywords: ['dollar', 'money', 'cash'], category: 'objects' },
    { emoji: '💎', keywords: ['diamond', 'gem', 'rich'], category: 'objects' },
    { emoji: '🎁', keywords: ['gift', 'present', 'birthday'], category: 'objects' },
    { emoji: '🔑', keywords: ['key', 'lock', 'secret'], category: 'objects' },
    { emoji: '⚙️', keywords: ['gear', 'settings'], category: 'objects' },
    { emoji: '🔥', keywords: ['fire', 'hot', 'lit'], category: 'objects' },
    { emoji: '💧', keywords: ['water', 'drop'], category: 'objects' },

    // More Symbols
    { emoji: '❤️', keywords: ['heart', 'love', 'red'], category: 'symbols' },
    { emoji: '💔', keywords: ['broken heart', 'sad'], category: 'symbols' },
    { emoji: '⭐', keywords: ['star', 'rating'], category: 'symbols' },
    { emoji: '🌟', keywords: ['glowing star', 'sparkle'], category: 'symbols' },
    { emoji: '💯', keywords: ['hundred', 'perfect', 'score'], category: 'symbols' },
    { emoji: '✅', keywords: ['check', 'done', 'complete'], category: 'symbols' },
    { emoji: '⏹️', keywords: ['stop', 'stopwatch', 'timer'], category: 'symbols' },
    { emoji: '⏳', keywords: ['stopwatch', 'timer'], category: 'symbols' },
    { emoji: '⏸️', keywords: ['pause', 'stop'], category: 'symbols' },
    { emoji: '⏯️', keywords: ['play/pause', 'media'], category: 'symbols' },
    { emoji: '⏺️', keywords: ['record', 'media'], category: 'symbols' },
    { emoji: '⏭️', keywords: ['next track', 'media'], category: 'symbols' },
    { emoji: '⏮️', keywords: ['previous track', 'media'], category: 'symbols' },
    { emoji: '⏩', keywords: ['fast forward', 'media'], category: 'symbols' },
    { emoji: '❎', keywords: ['cross', 'wrong', 'no'], category: 'symbols' },
    { emoji: '🔴', keywords: ['red circle', 'stop'], category: 'symbols' },
    { emoji: '🟡', keywords: ['yellow circle', 'warning'], category: 'symbols' },
    { emoji: '🟢', keywords: ['green circle', 'go'], category: 'symbols' },
    { emoji: '🟣', keywords: ['purple circle', 'magical'], category: 'symbols' },
    { emoji: '🟤', keywords: ['brown circle', 'earth'], category: 'symbols' },
    { emoji: '⚫', keywords: ['black circle', 'empty'], category: 'symbols' },
    { emoji: '⚪', keywords: ['white circle', 'empty'], category: 'symbols' },
    { emoji: '❌', keywords: ['cross', 'wrong', 'no'], category: 'symbols' },
    { emoji: '❓', keywords: ['question', 'mark'], category: 'symbols' },
    { emoji: '❗', keywords: ['exclamation', 'important'], category: 'symbols' },
    { emoji: '➡️', keywords: ['arrow', 'right'], category: 'symbols' },
    { emoji: '⬅️', keywords: ['arrow', 'left'], category: 'symbols' },
    { emoji: '⬆️', keywords: ['arrow', 'up'], category: 'symbols' },
    { emoji: '⬇️', keywords: ['arrow', 'down'], category: 'symbols' },
    { emoji: '💦', keywords: ['sweat droplets', 'sweat', 'bodily fluids', 'ejaculation', 'suggestive'], category: 'symbols' },
    { emoji: '💩', keywords: ['poop', 'shit', 'fart', 'feces', 'excrement', 'suggestive'], category: 'symbols' },
]